# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5173b5a0fffa8d1b35d4c0c7376be5ef5fada44acbeb1c1d8be0d5a9d0fba7a366824a04c87cfa9aa67144ddea526be513939c26bda47dff3eeb2a62a117ebc6

test:
  secret_key_base: 5173872e480b3ad343b228093283c60f75cf61b54e219839136f6d3caf8f2319650162b9bafc1f6a17f1f0253fd939435f1292f0f23e140591e352577f591dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
